boilerplate-setup.sh
The folder was still named `./types/ember-boilerplate` after running the `boilerplate-setup.sh` script.
=> Rename application types directory in setup script

BOILERPLATE_README.md, Makefile, package.json, scripts/enforce-engine-versions.js
Like we did in https://github.com/mirego/elixir-boilerplate/pull/15, we now require `node ~> 10.15` (not `node = 10.15.1`) and `npm ~> 6.4` (not `npm = 6.4.1`).
=> Do not freeze patch version for Node and NPM requirements

.stylelintrc, app/pods/home/template.hbs, app/router.ts, app/styles/app.scss
Like [we have](https://github.com/mirego/elixir-boilerplate/blob/master/lib/elixir_boilerplate_web/home/templates/index.html.eex) for `elixir-boilerplate`, we now have a home route and template to ensure that booting the project provides a working `200 OK` URL.
=> Add home route

.dockerignore, BOILERPLATE_README.md, Dockerfile, Makefile, config/environment.js, docker-compose.yml, package.json, scripts/ci-check.sh, scripts/docker-entrypoint.sh
The setup is pretty similar to [the one we have](https://github.com/mirego/react-boilerplate/blob/master/Dockerfile) in `react-boilerplate`.
And like in `react-boilerplate`, we need to _build_ the application when _running_ the image, not when _building_ it, because otherwise our setup wouldn’t be twelve-factor-compatible.
=> Add Docker setup

scripts/ci-check.sh
Although building the application perform a type check, the `ci-check` does not fail when type inconsistencies are found.
Running the type check separately ensures that `ci-check` fails when type inconsistencies are found; which is what we want I believe.
=> Suggestion: Add type checking in ci-check script.

Makefile, scripts/ci-check.sh
* We now use `lint-<stuff>` for targets that lint stuff
* We now use `format-<stuff>` for targets that format or _fix_ stuff
* We now use `check-<stuff>` for targets that check stuff (eg. types, formatting, code coverage, etc.)
* `lint-<tool>` and `format-<tool>` have been converted to `lint-<type>` and `format-<type>` (where `type` is `styles`, `scripts`, etc.)
* `dev-start` and `dev-stop` have been converted to the more accurate `services-start` and `services-stop` because they manage Docker Compose services
* We now store file patterns as variables at the top of the `Makefile` to make them more visible and prevent them from being hardcoded or duplicated deep down in the file
* Targets are now grouped:
* Build targets
* Development targets
* Check, lint and format targets
* Service …
=> Improve “make” target naming

scripts/enforce-engine-versions.js
Under older version of Node (< 10), we were facing a javascript error causing the script to fail instead of reporting the right behavior. Let's fix the Javascript and voila!
```shell
/Users/boubalou/dev/mirego/ember-boilerplate/assets/scripts/enforce-engine-versions.js:11
} catch {
^
SyntaxError: Unexpected token {
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:152:10)
at Module._compile (module.js:605:28)
at Object.Module._extensions..js (module.js:652:10)
at Module.load (module.js:560:32)
at tryModuleLoad (module.js:503:12)
at Function.Module._load (module.js:495:3)
at Function.Module.runMain (module.js:682:10)
at startup (bootstrap_node.js:191:16)
at bootstrap_node.js:613:3
```
After:
```shell
> ./scripts/enforce-engine-versions.js
Node.js 9.2.1
NPM 5.5.1
You are using …
```
=> Fix enforce-engine-version script with node < 10

types/ember-intl/services/intl.d.ts
Ember-intl `t()` current typing force optional parameters
Fix the function signature.
=> Make intl translate optional params really optional

ember-cli-build.js, package-lock.json, package.json
Since evergreen browsers need much less polyfilling than IE11, we use `ember-cli-babel-polyfills` to split them in 3 bundles: 
1. evergreen
2. legacy
3. shared
Loading of the bundles is handled by the `nomodule` flag, it makes sure we load the legacy bundle only in browsers that don’t support native JavaScript modules.
=> Use ember-cli-babel-polyfills to split Babel polyfills between evergreen and legacy browsers

Makefile
The check to see if SVG files are present never returned `true`, now it does!
=> Fix SVG file presence check

node-server/middleware/deduplicate-slashes.js, node-server/middleware/strip-trailing-slashes.js
The `URL` constructor expects a complete URL or a relative URL with a base URL, since we were passing only the relative part, it was throwing an error. Now we make sure to pass the base URL
=> Fix middleware URL parsing

node-server/server.js
The health check was working but always throwing an error due to the fact that we trying to set the status code after sending the body of the response.
=> Fix health check sending headers after body

service-worker/index.js
We were putting in service worker cache invalid responses in `cacheFirst` and `networkFirst` strategies. This resulted in invalid responses or errors being served to the user over and over again even if the problem was fixed on remote.
This PR fixes this issue by checking that the response is successful before caching it
=> Do not cache invalid network responses when using service worker

config/environment.js, config/utils.js, node-server/server.js
The integration didn’t work because of a little mistake from me: `asBoolean` only accepts "boolean" values, it doesn’t cast another type 😬 
So now, I added another utils for that case and we use it for activating Sentry
=> Fix Sentry integration

app/pods/not-found/route.ts, config/environment.js, config/utils.js, ember-cli-build.js, node-server/server.js
1. Set the status code correctly on the 404 page
2. Remove `graphql-tag` from the final bundle since GraphQL queries are precompiled and don’t need `graphql-tag` at runtime
3. Remove Babel config to add polyfills, it’s already taken care of by `ember-cli-babel-polyfills`
4. Make sure to never cache `/health`, `/robots.txt`, `sitemap.xml`, `/sw.js`
5. Use `cacheControl` middleware to cache assets
=> Bring back improvements from client project

docs/i18n-routing.md
The `Router`'s `dslCallbacks` array could cause memory leaks in applications.
We have to empty the `dslCallbacks` array from the `Router` in order to prevent memory leaks. Ember pushes all the routes into the `dslCallbacks` array every time this initializer is called. This can cause a memory leak since `dslCallbacks` is a global variable of `Router`.
See https://github.com/emberjs/ember.js/blob/d96d9aad52e010da977d813f479494397ee53ec6/packages/%40ember/-internals/routing/lib/system/router.ts#L1556.
=> Update the i18n routing documentation concerning the Router's dslCallbacks array

CHANGELOG.md, LICENSE.md, Makefile
We now have simpler and clearer Docker-related environment variables in our `Makefile`
```bash
$ DOCKER_REGISTRY=gcr.io/foo make
```
=> Improve Docker-related environment variables in Makefile

package-lock.json, package.json, tests/test-helper.js
The `chai-dom` package is currently installed in the boilerplate but it is not properly hooked to the test setup.
- Include it in the `test-helper.js`, just like we did for `sinon-chai`
- Install the types since `chai-dom` does not ship with its typings
=> Init chai dom

.eslintrc.js
With the previous configuration, we could not escape unused params and variables, which is sometime required when using positional params and arrays.
It is widely accepted that `_` prefixed variables are not used.
=> Add an eslint rule to escape unused variables

README.md
We had a private list of preferred libraries we use in our projets. There is no reason for this list to be private and can actually help boilerplate users to get started.
These libraries aren’t included by default in the boilerplate since they are not required in all our projects.
=> Add preferred libraries section in README.md

app/pods/application/template.hbs, app/templates/head.hbs, package-lock.json, package.json, translations/general/application/en-ca.json
We had nothing to set the page title in the boilerplate and pages should **always** have a significant title! 
I also fixed how we used `ember-cli-head` since the content was output in the body 😬
=> Add ember-page-title

node-server/server.js
Since the version `2.1.0` of [`forcedomain`](https://github.com/thenativeweb/forcedomain), the main export is no longer a default export, but a named export.
We fix our `node_module/server.js` file to reflect this change and fix the build script!
=> Fix the "forcedomain" require instruction in server.js

app/initializers/sentry.ts, app/services/-apollo.ts, config/environment.js, types/@sentry/ember/index.d.ts
The new `@sentry/ember` addon is only compatible with Embroider, now that we have it we can update our setup! 🎉 
=> Update Sentry setup

.github/workflows/ci.yaml, README.md
We’re no longer using Travis to run CI builds on the boilerplate project. Let’s use the proper badge!
=> Replace Travis badge with GitHub Actions badge

node-server/middleware/strip-trailing-slashes.js
When I refactored the server, I introduced a bug which caused the infamous Too Many Redirects error 😬  That’s now fixed!
=> Fix strip-slashes middleware

app/services/translations.ts, tests/unit/services/translations-test.ts
After testing the async translations setup in a real app I found out that the translation files were placed at the root instead of in the assets folder. I also fixed how we check for the translations presence since the shoebox always returns an object, not null.
=> Fix async translations setup

app/services/location/fastboot.ts, tests/unit/services/location/fastboot-test.ts
Update FastBoot location service to ensure that `path` is returning a value even if there is no query/hash in the URL.
With the actual code, `location.path` returns an empty string even if the URL is `localhost:4200/en`.
=> Update `FastbootLocation` service

app/services/location/fastboot.ts, tests/unit/services/location/fastboot-test.ts
There was a bug in both `path` and `queryString` methods for `FastBootLocation` where we assumed that a `#hash` would be present. I added a test for both methods and fixed the bug!
=> Fix bugs in FastBootLocation path and queryString methods
